// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpFXbQjUetTXVXFSFTxTKjBUCb1sOzPVY',
    appId: '1:833740885262:web:6d6e63ea9d358ad1d39b5f',
    messagingSenderId: '833740885262',
    projectId: 'fir-flutter-codelab-5e63e',
    authDomain: 'fir-flutter-codelab-5e63e.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-5e63e.firebasestorage.app',
    measurementId: 'G-BVJCY8WHH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD4CnaiGz1Joen7YDdMSnua_1fWG5gcKg',
    appId: '1:833740885262:android:eb47071a8c5bfcdfd39b5f',
    messagingSenderId: '833740885262',
    projectId: 'fir-flutter-codelab-5e63e',
    storageBucket: 'fir-flutter-codelab-5e63e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1HeuKyBePKp4Ys7iNnwy8lOfDE8wg4uA',
    appId: '1:833740885262:ios:9aed732f7699ddccd39b5f',
    messagingSenderId: '833740885262',
    projectId: 'fir-flutter-codelab-5e63e',
    storageBucket: 'fir-flutter-codelab-5e63e.firebasestorage.app',
    iosClientId: '833740885262-o3damrigi7kvr89r3dmun2l2p5i4j3lb.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1HeuKyBePKp4Ys7iNnwy8lOfDE8wg4uA',
    appId: '1:833740885262:ios:9aed732f7699ddccd39b5f',
    messagingSenderId: '833740885262',
    projectId: 'fir-flutter-codelab-5e63e',
    storageBucket: 'fir-flutter-codelab-5e63e.firebasestorage.app',
    iosClientId: '833740885262-o3damrigi7kvr89r3dmun2l2p5i4j3lb.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

}